permalink: /:title.html
markdown: kramdown
name: Bec d'état - Rebecca Scott's blog
url: https://becdetat.com
future: true

gems:
  - liquid

plugins:
  - jekyll-feed
  - jekyll-seo-tag

dependencies:
  - liquid